[package]
name = "dht-node"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["full"] }
hex = "*"
rand = "*"
byteorder = "*"
bendy = "*"
num-bigint = "*"
log = "*"
simplelog = { version = "*", features = ["paris"] }